events {}
http {
  upstream gateway_upstream {
    server gateway:8080;
  }

  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=20r/s;

  server {
    listen 80;

    location / {
      limit_req zone=api_limit burst=40 nodelay;
      proxy_pass http://gateway_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
